# Generated by Django 2.2.2 on 2019-06-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rest', '0003_auto_20190616_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
